### ISSUE TITLE
ember-cli-foundation-6-sass don't work

### ISSUE THREAD

**Issue by chmich** [acoustep/ember-cli-foundation-6-sass#100]
Hi all,

this nice addon seems not to work?

ember-cli version 10.6.0

`ember new ..`
`npm install --save-dev ember-cli-sass`
 `ember install ember-cli-foundation-6-sass`
 `ember g ember-cli-foundation-6-sass`
 `ember serve`

=> i get a blank page and console-message: `Could not find module foundation-sites imported from ember-cli-foundation-6-sass/initializers/zf-widget`

thanks,
chris

**Comment by GCheung55** [comment]
@chmich did you also add configuration to `ember-cli-build.js`? You'll need to add configuration if you want to use the components, by default the JS is not loaded.

From https://github.com/acoustep/ember-cli-foundation-6-sass#javascript

```javascript
    'ember-cli-foundation-6-sass': {
      'foundationJs': 'all'
    }
```

**Comment by chmich** [comment]
@GCheung: thanks - it works!
i understood this point as optional.

**Comment by allthesignals** [comment]
> i understood this point as optional.

Same - how do we exclude javascript from this?
