### ISSUE TITLE
Deprecation warning of Ember.$() in ember 3.9

### ISSUE THREAD

**Issue by alejomo** [acoustep/ember-cli-foundation-6-sass#103]
Fresh install Ember 3.9 i'm getting several warnings in the browser console:

DEPRECATION: Using Ember.$() has been deprecated, use `import jQuery from 'jquery';` instead [deprecation id: ember-views.curly-components.jquery-element] See https://emberjs.com/deprecations/v3.x#toc_jquery-apis for more details.

**Comment by therealbenhogan** [comment]
Hi, have the same issue (3.10)

**Comment by cesarizu** [comment]
I have a branch https://github.com/GovSciences/ember-cli-foundation-6-sass/tree/jquery-fix that fixes most of this.

**Comment by therealbenhogan** [comment]
Many thanks César - I'll take a look

**Comment by zion** [comment]
Same issue for me too on 3.11.

**Comment by zion** [comment]
@cesarizu Can you open a PR for this change? Maybe @acoustep can merge it in when he has time.

**Comment by acoustep** [comment]
I'm happy to merge if you submit a request 🙂

**Comment by cesarizu** [comment]
I've opened the PR at acoustep/ember-cli-foundation-6-sass#104 with the code that we've been using for quite some time. Please let me know if there's anything that I should change.

**Comment by acoustep** [comment]
Thanks @cesarizu! I have accepted and bumped the version number.

**Comment by zion** [comment]
Awesome work. Thanks!

**Comment by zion** [comment]
@acoustep should npm automatically acknowledge v26? It still says 25 is the latest

**Comment by acoustep** [comment]
@zion sorry I needed to publish the update. This is done now 👍

**Comment by zion** [comment]
Thanks mate!
