### ISSUE TITLE
How to edit SASS?

### ISSUE THREAD

**Issue by danilovaz** [acoustep/ember-cli-foundation-6-sass#11]
First, thank u for this project.

I need to change background-color off class .top-bar from $light-gray to $white, but if I change in node_modules/ember-cli-foundation-6-sass I will lost all changes in CSS. What the right in this case?

Ty.

**Comment by donaldwasserman** [comment]
Hey there - I'm new to this project, but depending on your project sass structure, you can include a _settings.scss file (see http://foundation.zurb.com/sites/docs/sass.html#the-settings-file) to make those changes. Let me know if you need more help!

**Comment by danilovaz** [comment]
Hi Donald!

Thank you for yor help.

So yes, I have this file in my project.

But the case is I want change variable is used in the class, but I only find file CSS foundation in node_modules, e.g:

FROM THIS:

.top-bar {
 background-color: $light-gray;
}

TO THIS

.top-bar {
 background-color: $white;
}

I don't know if I be clear with my question.

**Comment by acoustep** [comment]
Hi @danilovaz

After installing and running the generator you should have two SASS files inside of app/styles

There should be a _settings.scss file, and at the bottom there is a section for the topbar variables.

Does that help?

**Comment by acoustep** [comment]
Closing this for now.  Feel free to reopen if you're still having an issue.
