### ISSUE TITLE
"Uncaught Error: Assertion Failed: A helper named 'zf-tabs' could not be found"

### ISSUE THREAD

**Issue by cfator** [acoustep/ember-cli-foundation-6-sass#13]
// using foundation-sites v6.1

ember-cli-build.js:
module.exports = function (defaults) {
    var app = new EmberApp(defaults, {
        'ember-index': indexConfig,
        emberCliFontAwesome: {
            useScss: true
        },
        'ember-cli-foundation-6-sass': {
            'foundationJs': 'all'
        }
    }
);

Markup:
{{#zf-tabs}}
    {{#each otherAppSearches as |search|}}
        <li class="tabs-title">
            <a {{action 'changeHash' search.id}}>
                {{search.name}}
                <i class="fa fa1 fa-times close"></i>
            </a>
        </li>
    {{/each}}
{{/zf-tabs}}

Getting:
"Uncaught Error: Assertion Failed: A helper named 'zf-tabs' could not be found"

As soon as the tab control attempts to render.

Is there something I am missing to get the tab behaviors to work?

**Comment by acoustep** [comment]
Sorry for the delay, are you still getting this issue?

Tabs seems to work to fine with the latest version of this package. Can you tell me what version of Ember you are using?

**Comment by GCheung55** [comment]
I'm closing the issue because there hasn't been any response in the past year. Please file a new ticket if this is still an issue.
