### ISSUE TITLE
Is there a plan to upgrade to foundation 6.2.1?

### ISSUE THREAD

**Issue by nadavshatz** [acoustep/ember-cli-foundation-6-sass#20]
Wondering if there is a plan to upgrade this to foundation 6.2.1 and if a PR would help?

**Comment by acoustep** [comment]
PRs are more than welcome, I'll try and get on to this sorted tonight otherwise :)

**Comment by nadavshatz** [comment]
@acoustep great thanks. Let me know if it ends up falling between the cracks and I'll give it a go.

**Comment by acoustep** [comment]
I've updated the Foundation version in Bower. All of the components work except for offset canvas, which I haven't had a chance to look in to properly yet.

**Comment by kaermorchen** [comment]
@acoustep I also want to say thank you. I use foundation and your addon really helped me.

**Comment by acoustep** [comment]
@kaermorchen no problem, I'm glad it's helped!

**Comment by kaermorchen** [comment]
@acoustep a property "revealClass" not work in zf-off-canvas component.I try to do `{{#zf-off-canvas revealClass="reveal-for-large" as |section| }}` but class 'reveal-for-large' not added to element '.off-canvas.position-left'

**Comment by mako87** [comment]
@kaermorchen `{{#zf-off-canvas revealClass='large' as |section| }}`

**Comment by andycochran** [comment]
How about 6.4.1? 
(Should this issue be closed?)

**Comment by GCheung55** [comment]
Adding `revealClass="reveal-for-large"` for with foundation-sites@6.4.1 isn't working either. I just tried it on the dummy app.

What did work was going into `addon/templates/components/zf-off-canvas.hbs` and adding `reveal-for-large` class to the elements with `off-canvas` class.

Something like:

```handlebars
<div class="off-canvas position-left reveal-for-large" id="zf-off-canvas-left" data-off-canvas>
    {{yield offCanvasLeftContent}}
</div>
```

**Comment by GCheung55** [comment]
I've filed a ticket to address the `revealClass` issue, #83.

Closing issue because foundation-sites@6.4.1 is supported, though support is kind of buggy. Please re-open the ticket if you feel the ticket closure is in error.
