### ISSUE TITLE
SASS Issues Loading normalize-scss/sass/normalize

### ISSUE THREAD

**Issue by benbabics** [acoustep/ember-cli-foundation-6-sass#40]
I have a feeling this has to do with `foundation-sites` codebase, but here goes...

I have a fresh install of foundation-sites v6.3.0, and it is bombing out during my build complaining about being unable to load `../_vendor/normalize-scss/sass/normalize`. 

Please see output below:

```
File: /tmp/sass_compiler-input_base_path-djMaZN2O.tmp/1/foundation.scss (9)
The Broccoli Plugin: [SassCompiler] failed with:
Error: File to import not found or unreadable: ../_vendor/normalize-scss/sass/normalize
Parent style sheet: /tmp/sass_compiler-input_base_path-djMaZN2O.tmp/1/foundation.scss
    at options.error (/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/lib/index.js:286:26)
```

Any help is much appreciated. Thanks!

**Comment by wlbrough** [comment]
Check out this thread from ember-cli-sass: https://github.com/aexmachina/ember-cli-sass/issues/124

It looks like by moving the `_vendor` directory to be a sibling to the `scss` directory, it breaks the build all the way down to broccoli. I'm trying to figure out some kind of hack to get around this, because it looks to go a few layers deep.

**Comment by wlbrough** [comment]
Not a long-term solution, but I copied the `_vendor` folder into the `scss` folder and then changed the references in `foundation.scss` to reference that folder (i.e. get rid of the `../` in front of `../_vendor`). There are seven references in total, right at the top of the file. 

Obviously that's not sustainable, but it will keep me working for the time being. I thought I was going to be able to fix it with a pull request to the ember-cli-sass project, but it really is a broccoli issue. Only thing I can think of is taking this out of the broccoli toolchain and the addon can just do the sass build step with gulp.

**Comment by wlbrough** [comment]
I ended up writing a shell script to copy the directory and rewrite the references. Hackier solution than I would like, but it will have to do for the time being. At least it will pass my CI.

Added `.bower-postinstall.sh` to the root directory:
```
#!/bin/bash

# Foundation Sites move _vendor directory inside scss directory and update refs
mv bower_components/foundation-sites/_vendor bower_components/foundation-sites/scss
sed -i 's/\.\.\/_vendor/_vendor/g' bower_components/foundation-sites/scss/foundation.scss
```

Then added to the `.bowerrc` file:
```
"scripts": {
  "postinstall": "./.bower-postinstall.sh"
}
```

Make the script executable:
`chmod +x .bower-postinstall.sh`

**Comment by benbabics** [comment]
Yep... not ideal, but it works for now to get the codebase up and running for my team. Only change I had to make was to have an empty string in the sed command of `.bower-postinstall.sh` for OSX. Other than that, it works for well for us now. Thx

**Comment by bravo-kernel** [comment]
Just wondering, will this script be a/the permanent solution?

**Comment by ccbergstrom** [comment]
Have to modify the sed command to avoid an `undefined label` error on Mac OS X. Here's the refined `.bower-postinstall.sh` with an added empty argument to pass.
```
#!/bin/bash

# Foundation Sites move _vendor directory inside scss directory and update refs
mv bower_components/foundation-sites/_vendor bower_components/foundation-sites/scss
sed -i '' 's/\.\.\/_vendor/_vendor/g' bower_components/foundation-sites/scss/foundation.scss
```

**Comment by GCheung55** [comment]
So what I've tried is to create a broccoli funnel that just contains the `_vendor` and `scss`, and add the funnel to `includePaths` array.

Doing so gives me a slightly different error:

```
File: /git/ember-cli-foundation-6-sass/tmp/sass_compiler-input_base_path-jViEviNJ.tmp/0/app/styles/app.scss (1)
File to import not found or unreadable: foundation
Parent style sheet: /git/ember-cli-foundation-6-sass/tmp/sass_compiler-input_base_path-jViEviNJ.tmp/0/app/styles/app.scss
Error: File to import not found or unreadable: foundation
Parent style sheet: /git/ember-cli-foundation-6-sass/tmp/sass_compiler-input_base_path-jViEviNJ.tmp/0/app/styles/app.scss
    at options.error (/git/ember-cli-foundation-6-sass/node_modules/node-sass/lib/index.js:272:32)
```

This just means that `foundation` itself is not available and requires changing `app.scss`.

```scss
// The old way
//@import 'foundation';
// The new way
@import 'scss/foundation`;
```

I don't like having to access foundation via `scss/foundation` though, so I think accessing `foundation-sites/foundation` makes more sense.
