### ISSUE TITLE
Are the Foundation 6 plugins unsupported?

### ISSUE THREAD

**Issue by bravo-kernel** [acoustep/ember-cli-foundation-6-sass#42]
This is probably due to my lack of expertise but I'm unable to set up a simple sticky. If somebody could provide me with an example I will create a PR for the docs.  Thanks in advance.

**Comment by bravo-kernel** [comment]
Hmmm, it seems the Ember component for Sticky is missing (even though it is mentioned in the Readme). Am I missing something obvious here?

**Comment by bmx269** [comment]
I was interested in the same thing. Even using the sticky data- attributes does not allow it to work. Is the sticky js lib being loaded with the addon?

**Comment by bravo-kernel** [comment]
It seems the same applies for all entries under the Foundation 6 `Plugins` category:

- Abide
- Equalizer
- Interchange
- Toggler
- Sticky

If somebody could confirm they are NOT supported by this repo I will update the readme.

**Comment by bravo-kernel** [comment]
@bmx269 if you are still interested,  was able to whip up this very simplistic sticky component which produces a sticky header (with accompanying height/width alterations done by the foundation javascript when e.g. resizing the browser).

```javascript
import Ember from 'ember';

export default Ember.Component.extend({
  didInsertElement: function() {
    this._super(...arguments);
    let element = this.$('#header');
    let elem = new Foundation.Sticky(element, {
      "data-stick-to": "top",
    });
  }
});
```

```handlebars
<div data-sticky-container data-top-anchor="1">
    <div id="header" class="title-bar" data-sticky data-top-anchor="1">
        {{yield}}
    </div>
</div>
```

**Comment by bravo-kernel** [comment]
Totally works cross desktop and mobile using this codepen http://codepen.io/brettsmason/pen/adbYXV (when `id="header` is added to the `data-sticky` div.

Hope this helps someone. Creating the component for this repo is one bridge too far for me atm.

**Comment by bravo-kernel** [comment]
Updated above component code with a fix that will guarantee stick on every mobile/browser. 

The `this.$(window).trigger('load.zf.sticky');` part does the trick.

**Comment by bmx269** [comment]
That is awesome. Thanks.

**Comment by andycochran** [comment]
I'm still having trouble with Sticky.
```js
"ember-cli-foundation-6-sass": "0.0.24",
"foundation-sites": "^6.4.1",
```
Doesn't stick. 
😞
