### ISSUE TITLE
Reveal not working across multiple loads

### ISSUE THREAD

**Issue by tomtom5152** [acoustep/ember-cli-foundation-6-sass#53]
I'm trying to use a reveal in an ember loaded route, it works the first time you load the route, but it will fail to add the `data-reveal` attribute on subsequent load.

Versions
Ember: 2.10
ember-cli-foundation-6-sass: 0.0.18
foundation-6: 6.3.0

**Comment by GCheung55** [comment]
Do you have an example code to help reproduce the issue?

**Comment by tomtom5152** [comment]
This [gist](https://gist.github.com/tomtom5152/13f909eae563089dfc3ff7bab400d76f) is a trimmed version of the code I'm using, it isn't limited to any one of the reveals in particular, and occurs even when there is only one on the page.

Further investigation into the state of the dom shows this might be related to #26 as there are multiple elements with the same ID (it's being recreated with each load)

**Comment by tomtom5152** [comment]
Indeed this can be fixed by manually ensuring that the reveal element is removed in `zf-widget`. I don't know the foundation library well enough to know if this is a safe action, else I would submit a PR with the fix.

zf-widget.js:76
```js
    // Finally destory everything else.
    let zfUiList = this.get('zfUiList'),
      element = ui.$element;
    for (let zfUi of zfUiList) {
      zfUi.destroy();
    }
    element.remove();
```

**Comment by tomtom5152** [comment]
Having checked further, whilst this does fix the problem when actually using it, it completely breaks the test container for automated testing which is less than ideal.

**Comment by GCheung55** [comment]
@tomtom5152 Perhaps the element.remove() needs to be done within a run loop?

```javascript
 run.schedule('render', () => {
    element.remove();
});
```

The whole destroy/remove should be done within the run loop?

Do you have a test repo or reproducible steps? I'd like to look into the test container breaking issue.

**Comment by tomtom5152** [comment]
That does indeed appear to have fixed the issue
