### ISSUE TITLE
Flash message component

### ISSUE THREAD

**Issue by donaldwasserman** [acoustep/ember-cli-foundation-6-sass#57]
Hey there - 

I've been enjoying this project a lot.

Would you be interested in adding a flash-message-compatable component for this library? 

(If so, I'd be happy to submit a PR).

The https://github.com/poteto/ember-cli-flash project uses foundation5, so just providing a component that basically adds the right markup.

**Comment by acoustep** [comment]
That sounds useful @donaldwasserman, A PR would be most welcome :)
