### ISSUE TITLE
Deprecation warning due to dependencies listed as 'devDependencies' as of Ember 2.12.0

### ISSUE THREAD

**Issue by HaithamMaya** [acoustep/ember-cli-foundation-6-sass#58]
As of Ember 2.12.0, receive the following deprecation error:

DEPRECATION: Addon files were detected in `/Users/USER/Documents/Development/ember-vibe/node_modules/ember-cli-foundation-6-sass/addon`, but no JavaScript preprocessors were found for `ember-cli-foundation-6-sass`. Please make sure to add a preprocessor (most likely `ember-cli-babel`) to in `dependencies` (NOT `devDependencies`) in `ember-cli-foundation-6-sass`'s `package.json`.

**Comment by mirague** [comment]
I can confirm and reproduce by upgrading from Ember 2.11.0 to **2.12.0**.
