### ISSUE TITLE
Installing with ember-cli@2.13.1

### ISSUE THREAD

**Issue by danielrestrepo** [acoustep/ember-cli-foundation-6-sass#68]
Hi, I am not being able to install it with ember-cli 2.13.1 I just ran `ember install ember-cli-foundation-6-sass` and the error

```bash
Yarn: Installed ember-cli-foundation-6-sass
ember-cli-htmlbars-inline-precompile@0.3 requires the host to use ember-cli-babel@5. To use ember-cli-babel@6 please upgrade ember-cli-htmlbars-inline-precompile to 0.4.
```
I tried to follow the upgrade path suggested on the error but it ends up in nothing, just circular errors.

![Terminal capture]
(https://lh3.googleusercontent.com/-nsem34Tg5ek/WQ8t-lI5PEI/AAAAAAAAcl8/bxGCRwSlSCETG7PeJImNEi5fum2xiD4GQCL0B/h570/daniel%2540dnipro%253A%2B%257E-dev-todo-list-2_021.png)

**Comment by donaldwasserman** [comment]
This is a problem with many addons in cli 2.13 (there's a pretty lengthy chat about it in the ember-cli channel in the ember community slack). 

I have a (#69) PR that should address it.

**Comment by danielrestrepo** [comment]
Thanks a lot, for now I am using it like this:
```json
"dependencies": {
    //..,
    "ember-cli-foundation-6-sass": "git://github.com/donaldwasserman/ember-cli-foundation-6-sass#update",
    //..
  }
```
Hope your PR gets merged soon.
Cheers

**Comment by acoustep** [comment]
Merged it, I'll publish an update when I get home in a couple of hours :)

**Comment by danielrestrepo** [comment]
Great! Cheers! :)
