### ISSUE TITLE
Move away from bower.

### ISSUE THREAD

**Issue by GCheung55** [acoustep/ember-cli-foundation-6-sass#70]
Ember is moving to a non-bower world.

* Update blueprint to install `foundation-sites` from npm.
* Update `index.js` to reference the `foundation-sites` in node_modules.
* Add backwards compat.

I think installing `foundation-sites` bower also adds `what-input ` and `jquery` automatically, and it looks like those deps are listed in `foundation-sites` package.json as well. I'm not sure whether they will need to be loaded or not though.

**Comment by acoustep** [comment]
Agreed, I think this would be a good move.
