### ISSUE TITLE
How to access myRevealComponent

### ISSUE THREAD

**Issue by jamiechong** [acoustep/ember-cli-foundation-6-sass#73]
Your docs mention this: 

> Each Foundation Javascript widget can be directly accessed through the zfUi property. For example, the following would call the open method on the reveal component:
> 
> `myRevealComponent.get('zfUi').open();`
> 

Where does the reference to `myRevealComponent` come from?

**Comment by GCheung55** [comment]
It's no documented but `zfUi` is a property that you can pass into the reveal component to access later. 

```javascript

{{#zf-reveal zfUi=zfRevealInstanceOnControllerOrComponent}}
Reveal Me!
{{/zf-reveal}}
```

`zfRevealInstanceOnControllerOrComponent` is just a property so when `zf-reveal` component sets `zfUi` it will be accessible by the controller or component that passed in the property.
